name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

jobs:
  # Test crates on their minimum Rust versions and nightly Rust.
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      RUST_VERSION: ${{ matrix.rust }}
    strategy:
      matrix:
        crates:
          - crossbeam
          - crossbeam-channel
          - crossbeam-deque
          - crossbeam-epoch
          - crossbeam-queue
          - crossbeam-skiplist
          - crossbeam-utils
        rust:
          - 1.28.0
          - nightly
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Add targets
        if: matrix.rust == 'nightly'
        run: |
          rustup target add thumbv7m-none-eabi
          rustup target add thumbv6m-none-eabi
      # cfg-if 0.1.10 requires Rust 1.31+ so downgrade it.
      - name: Downgrade dependencies
        if: matrix.rust == '1.28.0'
        run: |
          cargo generate-lockfile
          cargo update -p cfg-if --precise 0.1.9
      - name: Test
        run: ./ci/${{ matrix.crates }}.sh

  # Check for duplicate dependencies.
  dependencies:
    name: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update nightly && rustup default nightly
      - name: dependency tree check
        run: ./ci/dependencies.sh

  # Check formatting.
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: rustfmt
        run: ./ci/rustfmt.sh
